# Generated by Django 3.1.1 on 2020-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20201118_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='posts/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
